version: '2.0.{build}.0'

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore Solutions\HtmlAgilityPack.4.5.sln

build:
  parallel: true
  project: 'Solutions\HtmlAgilityPack.4.5.sln'
  
artifacts:
  path: NuGet